baseURL = "https://toyonagataminosuke.github.io"
languageCode = "en-us"
title = "とよなが君dayo!"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "powered by toyonaga"
    githubUsername = "#"
    accent = "red"
    showBorder = true
    backgroundColor = "Purple"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "ほめ"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "あぼうｔ"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "ぽｓｔｓ"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "ｐろじぇｃｔｓ"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.



[[menu.icon]]
    url = "https://github.com/toyonagataminosuke/"
    name = "fab fa-github"
    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "fab fa-twitter"
#    weight = 3

#[[menu.icon]]
#    url = "https://www.linkedin.com/in/username/"
#    name = "fab fa-linkedin"
#    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "fab fa-stack-overflow"
#    weight = 5
